### ISSUE TITLE
Delete all files in a folder

### ISSUE THREAD

**Issue by rylew2** [koltyakov/sppurge#4]
Requesting deletion of all files in a folder

```
var options = {
  folder: "/_catalogs/masterpage/spf/module_name",
  filePath: "/scripts/*.*"
};
```

**Comment by koltyakov** [comment]
Hey @rylew2,

 The feature is delivered:

- [Delete a folder](https://github.com/koltyakov/sppurge/blob/master/test/deleteUsingRegExp.ts) - actually this functionality was in the library before;
- [Delete files based on regular expression](https://github.com/koltyakov/sppurge/blob/master/test/deleteUsingRegExp.ts) - this was added.

The second option provides a flexible approach, it requests for all files inside a specific folder and its subfolders, then delete only files which server-relative paths correspond a regular expression.

**Comment by SyedRizvi01** [comment]
@koltyakov I tried using the regular expression _fileRegExp: new RegExp('(.*)/(.*)\.(js)', 'i')_ and it's not working for me. My use case is to delete all the js files from the folder. I'm getting the following error. Deleting a particular file works for me.

**Error in getFolderContent: 400 - {"error":{"code":"-2147024809, System.ArgumentE
xception","message":{"lang":"en-US","value":"Server relative urls must start wit
h SPWeb.ServerRelativeUrl"}}}**

**Comment by SyedRizvi01** [comment]
@koltyakov  Please find the following gulp task where deleting a single file works for me. However, deleting all the js/map files in the folder isn't working for me.

```
build.task("delete-assets", {
  execute: (config) => { 
  const context = {
    siteUrl: config.production ? production.absoluteUrl : test.absoluteUrl,
    username: config.production ? production.username : test.username,
    password: config.production ? production.password : test.password
    };

    var options = {
      folder: `/${config.production ? production.libraryPath : test.libraryPath}`,
      fileRegExp: new RegExp('/(.*)\.(js|map)', 'i')
       // filePath: '/test.js' // This one is working for me
    };
   
    return sppurge(context, options);
  }
});
```

**Comment by koltyakov** [comment]
@SyedRizvi01, please make sure that you provide a valid server-relative URL for the `folder` parameter.

**Comment by SyedRizvi01** [comment]
@koltyakov I guess I'm providing a valid server-relative URL as it's working for me in case of a single file.

**Comment by koltyakov** [comment]
But the error message from the API says `Server relative urls must start with SPWeb.ServerRelativeUrl`. 

Which means that... let's say your web + folder have `https://contoso.sharepoint.com/sites/site-a/subsite/doclib/folder` URL, server relative, in this case, is equal to `/sites/site-a/subsite/doclib/folder`, but the URL provided is probably something like `/subsite/doclib/folder` or `//sites/site-a/subsite/doclib/folder`, in other words not a valid relative URL. If to follow the error message this is what I think of. Probably something else, however, there is not enough info.

**Comment by SyedRizvi01** [comment]
@koltyakov Apologies for the late response. I was on leave and didn't get a chance to test it on my machine. Thanks! It works for me now. It works differently for single file and regex. In case of single file you don't have to provide server relative URL for folder option. Providing complete siteUrl is good enough. However, one needs to provide relative URL for folder in case of regex.
