### ISSUE TITLE
Allow passing in fullUrl to options

### ISSUE THREAD

**Issue by rylew2** [koltyakov/sppurge#7]
Can you include the code to getWebByAnyChildUrl to find the correct web and allow passing in of a fullUrl to a file?

**Comment by koltyakov** [comment]
Added file deletion mechanism without providing specific site URL:

```javascript
const { SPPurge } = require('sppurge');
const sppurge = new SPPurge();

const creds = { /* auth context */ };
const filesArr = [
  'https://contoso.sharepoint.com/sites/site1/web1/lib1/folder1/folder2/file1.ext',
  'https://contoso.sharepoint.com/sites/site1/web1/lib2/folder1/file2.ext',
  'https://contoso.sharepoint.com/sites/site2/web2/lib3/folder/folder1/file3.ext',
  'https://contoso.sharepoint.com/sites/site3/web3/lib4/folder/folder1/file4.ext'
];

(async () => {
  for (const fileAbsolutePath of filesArr) {
    await sppurge.deleteFileByAbsolutePath(creds, fileAbsolutePath);
  }
  console.log('Done')
})()
  .catch(console.log);
```

@rylew2, could you please check?

**Comment by rylew2** [comment]
Worked great for simple url. It said Invalid Type when I put %20 for space in the url.  Might need to do a `decodeURI` first? When I copy a link address in chrome from the document library I get it encoded with %20. 

Working: 'https://contoso.sharepoint.com/sites/site1/web1/lib1/folder1/folder2/file1.ext''

Not Working: 'https://contoso.sharepoint.com/sites/site1/web1/lib1/My Spaced File.txt'

**Comment by koltyakov** [comment]
Pushed a fix for this.

**Comment by rylew2** [comment]
It works now - thanks!

**Comment by koltyakov** [comment]
Cool, closing the issue.
