### ISSUE TITLE
SPPurge error - cannot read property restApi

### ISSUE THREAD

**Issue by rylew2** [koltyakov/sppurge#8]
Had an issue running sppurge when it tries to delete the main js file for create-react-app:

`[10:57:24] SPPurge: /InfoCenter/static/js/main.270cf12d.js (delete) (node:13832) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'restApi' of undefined at \InfoCenter\node_modules\sppurge\dist\SPPurge.js:67:49 at step (\InfoCenter\node_modules\sppurge\dist\SPPurge.js:32:23) at Object.next (\InfoCenter\node_modules\sppurge\dist\SPPurge.js:13:53) at \InfoCenter\node_modules\sppurge\dist\SPPurge.js:7:71 at new Promise (<anonymous>) at __awaiter (\InfoCenter\node_modules\sppurge\dist\SPPurge.js:3:12) at \Desktop\InfoCenter\node_modules\sppurge\dist\SPPurge.js:55:24 (node:13832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2) (node:13832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

On Node 10.5

**Comment by koltyakov** [comment]
Thanks, @rylew2!
Fixed in 2.0.3.
