### ISSUE TITLE
Folder delete is not working

### ISSUE THREAD

**Issue by anfasci** [koltyakov/sppurge#9]
@koltyakov 

Core error has happened TypeError: Cannot read property 'replace' of undefined
node_modules/sp-request/lib/src/core/SPRequest.js:80:31

router.use("/deleteFolder/:folderName", async (req, res, next) => {
  var folderName = req.params.folderName;
  const authContext = {
    siteUrl: appConstants.conf.OTB_RESOURCE_URI2,
    creds:{
      clientId: appConstants.conf.AUD,
      clientSecret: appConstants.conf.CLIENT_SECRET,
      realm: appConstants.conf.TENANT_ID
    }
  };
  const relativeUrl = 'sites/doument/Shared Documents/Test1/' + folderName;
  let sppurge = new Delete();
  sppurge.deleteFolder(authContext, relativeUrl)
    .then(_ => {
      console.log('Folder has been deleted');
      const r = {
        message: 'Folder Deleted!'
      }
      res.status(200).json(r);
    })
    .catch(error => {
      console.log('Core error has happened', error);
      res.status(400).json(JSON.parse(error.error));
    });

});

**Comment by koltyakov** [comment]
Hi @anfasci, 

The error comes from the external library, so not sure what it can be.
However, `relativeUrl` looks incorrect:

![image](https://user-images.githubusercontent.com/7816483/59839498-5fcaa800-9359-11e9-8570-a3a4cd90475f.png)

**Comment by anfasci** [comment]
Not working

I changed to 
const relativeUrl = '/sites/doument/Shared Documents/Test1/' + folderName; also

**Comment by koltyakov** [comment]
The error from the SPRequest library means that no siteUrl has been provided:

![image](https://user-images.githubusercontent.com/7816483/59844004-732e4100-9362-11e9-9059-87a2781860be.png)

Can you verify that siteUrl is not empty? Full stack trace also can be helpful.
The scenario is covered with tests so I don't think it's something on the library side.

**Comment by anfasci** [comment]
Core error has happened { StatusCodeError: 403 - {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}}

**Comment by koltyakov** [comment]
So what was the error? Empty siteUrl?
Glad you've figured out that the Add-In has no permissions for a corresponding operation and resource.

**Comment by anfasci** [comment]
siteUrl was undefined.
But this issue exist.

Core error has happened { StatusCodeError: 403 - {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}}

**Comment by koltyakov** [comment]
It's not an issue. This is a signal from the server that the app has no permissions.

**Comment by anfasci** [comment]
I can delete and upload and dowload files. but cannot delete folder.

**Comment by koltyakov** [comment]
What can I say more than your Add-In just has no permissions? It's server configuration.

Try [changing Add-In permissions level](https://github.com/s-kainet/node-sp-auth/wiki/SharePoint-Online-addin-only-authentication#configuration-required).

E.g.:

```xml
<AppPermissionRequests AllowAppOnlyPolicy="true">
  <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl" />
</AppPermissionRequests>
```

**Comment by anfasci** [comment]
at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  name: 'StatusCodeError',
  statusCode: 403,
  message: '403 - {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}}',
  error: 
   { error: 
      { code: '-2147024891, System.UnauthorizedAccessException',
        message: [Object] } },

**Comment by anfasci** [comment]
Its already given

**Comment by anfasci** [comment]
_header: 'POST /_api/Web/GetFolderByServerRelativeUrl(@FolderPath)?@FolderPath=%27%2Fsites%2FNetspective_devl_test%2FShared%20Documents%2FTest1%2FFolder2%27

**Comment by anfasci** [comment]
Any solution?

**Comment by koltyakov** [comment]
No really! The solution is to grant permissions :D
It's not on the libraries end. 💯

**Comment by anfasci** [comment]
I given full access control for the user but got permission error

**Comment by koltyakov** [comment]
User? In your first message, you're using Add-In Only permissions.
Once again, not an issue and not on the library side. Sorry, closing this one.
